# Generated by Django 4.1 on 2022-08-20 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_remove_category_category_url_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, unique=True)),
                ('product_name_card', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('product_discription', models.TextField(blank=True)),
                ('product_highlights', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('pro_image1', models.ImageField(upload_to='images/products ')),
                ('pro_image2', models.ImageField(upload_to='images/products ')),
                ('pro_image3', models.ImageField(upload_to='images/products ')),
                ('pro_image4', models.ImageField(upload_to='images/products ')),
                ('pro_image5', models.ImageField(upload_to='images/products ')),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
    ]
