# Generated by Django 4.1 on 2022-08-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_image2',
            field=models.ImageField(blank=True, upload_to='images/products '),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_image3',
            field=models.ImageField(blank=True, upload_to='images/products '),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_image4',
            field=models.ImageField(blank=True, upload_to='images/products '),
        ),
        migrations.AlterField(
            model_name='products',
            name='pro_image5',
            field=models.ImageField(blank=True, upload_to='images/products '),
        ),
    ]
