# Generated by Django 4.0.7 on 2022-08-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('variant', 'variant'), ('color', 'color')], max_length=100),
        ),
    ]
