# Generated by Django 4.0.7 on 2022-09-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_discription1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_discription2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_highlights1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_highlights2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_highlights3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='product_highlights4',
            field=models.TextField(blank=True),
        ),
    ]
