# Generated by Django 4.1 on 2022-08-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(help_text='Enter 10 digits phone number', unique=True, verbose_name='Phone Number'),
        ),
    ]
