# Generated by Django 4.0.7 on 2022-09-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_offers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offers',
        ),
    ]
