# Generated by Django 4.0.7 on 2022-09-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisemennt', '0002_iconadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(upload_to='images/add')),
            ],
        ),
    ]
