# Generated by Django 4.0.7 on 2022-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisemennt', '0004_alter_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='images/wrapper')),
            ],
        ),
    ]
