# Generated by Django 4.0.7 on 2022-09-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
