# Generated by Django 4.0.7 on 2022-09-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_is_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
