# Generated by Django 4.0.7 on 2022-09-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
